### ISSUE TITLE
Unable to verify DC games

### ISSUE THREAD

**Issue by buvk** [j68k/verifydump#15]
Hi, I am having issues verifying DC games.  My set is bin/cue which I converted to CHD.  Scanning them returns the following error:

```
E:\Console\Games\TEST>verifydump.exe "Sega - Dreamcast - Datfile (1437) (2022-07-01 11-43-16).zip" e:\dc_test
Datfile loaded successfully with 1437 games
1 dump had an error:mplete...
SHA-1 of dump file "Tony Hawk's Pro Skater (USA) (Track 2).bin" doesn't match any file in the Dat
```

**Comment by j68k** [comment]
Unfortunately converting from bin/cue to chd with chdman is broken at the moment for Dreamcast games. It appears to work, but chdman ignores the Dreamcast-specific stuff in the .cue so it silently makes a broken chd. It *does* work fine, though, if you convert from bin/gdi.

When I converted my collection I downloaded the .gdi files from [Redump's download page](http://redump.org/downloads/), and put them in a folder with the uncompressed bin files from the bin/cue dump and pointed chdman at the .gdi.

Can you try that and see if it works?

**Comment by buvk** [comment]
If I replace the cue with a gdi I can verify successfully.

```
E:\Console\Games\TEST>verifydump.exe "Sega - Dreamcast - Datfile (1437) (2022-07-01 11-43-16).zip" e:\dc_test
Datfile loaded successfully with 1437 games
Dump verified correct and complete: "Tony Hawk's Pro Skater 2 (USA)"
```

**Comment by j68k** [comment]
Oh cool, glad it's working, and thanks for letting me know. I'll close this issue for now but feel free to reopen or open another if you have any more problems.
